/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppTrabalhosRouteImport } from './routes/_authenticated.app.trabalhos'
import { Route as AuthenticatedAppPlanosRouteImport } from './routes/_authenticated.app.planos'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated.app.perfil'
import { Route as AuthenticatedAppMatematicaRouteImport } from './routes/_authenticated.app.matematica'
import { Route as AuthenticatedAppFerramentasRouteImport } from './routes/_authenticated.app.ferramentas'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated.app.chat'
import { Route as AuthenticatedAppApresentacoesRouteImport } from './routes/_authenticated.app.apresentacoes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTrabalhosRoute =
  AuthenticatedAppTrabalhosRouteImport.update({
    id: '/trabalhos',
    path: '/trabalhos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPlanosRoute = AuthenticatedAppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMatematicaRoute =
  AuthenticatedAppMatematicaRouteImport.update({
    id: '/matematica',
    path: '/matematica',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFerramentasRoute =
  AuthenticatedAppFerramentasRouteImport.update({
    id: '/ferramentas',
    path: '/ferramentas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppApresentacoesRoute =
  AuthenticatedAppApresentacoesRouteImport.update({
    id: '/apresentacoes',
    path: '/apresentacoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/apresentacoes': typeof AuthenticatedAppApresentacoesRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/ferramentas': typeof AuthenticatedAppFerramentasRoute
  '/app/matematica': typeof AuthenticatedAppMatematicaRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/planos': typeof AuthenticatedAppPlanosRoute
  '/app/trabalhos': typeof AuthenticatedAppTrabalhosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/apresentacoes': typeof AuthenticatedAppApresentacoesRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/ferramentas': typeof AuthenticatedAppFerramentasRoute
  '/app/matematica': typeof AuthenticatedAppMatematicaRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/planos': typeof AuthenticatedAppPlanosRoute
  '/app/trabalhos': typeof AuthenticatedAppTrabalhosRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/apresentacoes': typeof AuthenticatedAppApresentacoesRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/app/ferramentas': typeof AuthenticatedAppFerramentasRoute
  '/_authenticated/app/matematica': typeof AuthenticatedAppMatematicaRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/planos': typeof AuthenticatedAppPlanosRoute
  '/_authenticated/app/trabalhos': typeof AuthenticatedAppTrabalhosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app'
    | '/app/apresentacoes'
    | '/app/chat'
    | '/app/ferramentas'
    | '/app/matematica'
    | '/app/perfil'
    | '/app/planos'
    | '/app/trabalhos'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/apresentacoes'
    | '/app/chat'
    | '/app/ferramentas'
    | '/app/matematica'
    | '/app/perfil'
    | '/app/planos'
    | '/app/trabalhos'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/app'
    | '/_authenticated/app/apresentacoes'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/ferramentas'
    | '/_authenticated/app/matematica'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/planos'
    | '/_authenticated/app/trabalhos'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trabalhos': {
      id: '/_authenticated/app/trabalhos'
      path: '/trabalhos'
      fullPath: '/app/trabalhos'
      preLoaderRoute: typeof AuthenticatedAppTrabalhosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/planos': {
      id: '/_authenticated/app/planos'
      path: '/planos'
      fullPath: '/app/planos'
      preLoaderRoute: typeof AuthenticatedAppPlanosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/matematica': {
      id: '/_authenticated/app/matematica'
      path: '/matematica'
      fullPath: '/app/matematica'
      preLoaderRoute: typeof AuthenticatedAppMatematicaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ferramentas': {
      id: '/_authenticated/app/ferramentas'
      path: '/ferramentas'
      fullPath: '/app/ferramentas'
      preLoaderRoute: typeof AuthenticatedAppFerramentasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/apresentacoes': {
      id: '/_authenticated/app/apresentacoes'
      path: '/apresentacoes'
      fullPath: '/app/apresentacoes'
      preLoaderRoute: typeof AuthenticatedAppApresentacoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppApresentacoesRoute: typeof AuthenticatedAppApresentacoesRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppFerramentasRoute: typeof AuthenticatedAppFerramentasRoute
  AuthenticatedAppMatematicaRoute: typeof AuthenticatedAppMatematicaRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppPlanosRoute: typeof AuthenticatedAppPlanosRoute
  AuthenticatedAppTrabalhosRoute: typeof AuthenticatedAppTrabalhosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppApresentacoesRoute: AuthenticatedAppApresentacoesRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppFerramentasRoute: AuthenticatedAppFerramentasRoute,
  AuthenticatedAppMatematicaRoute: AuthenticatedAppMatematicaRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppPlanosRoute: AuthenticatedAppPlanosRoute,
  AuthenticatedAppTrabalhosRoute: AuthenticatedAppTrabalhosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
