/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppTradutorRouteImport } from './routes/_authenticated.app.tradutor'
import { Route as AuthenticatedAppTrabalhosRouteImport } from './routes/_authenticated.app.trabalhos'
import { Route as AuthenticatedAppResumoRouteImport } from './routes/_authenticated.app.resumo'
import { Route as AuthenticatedAppPlanosRouteImport } from './routes/_authenticated.app.planos'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated.app.perfil'
import { Route as AuthenticatedAppMatematicaRouteImport } from './routes/_authenticated.app.matematica'
import { Route as AuthenticatedAppFerramentasRouteImport } from './routes/_authenticated.app.ferramentas'
import { Route as AuthenticatedAppCorretorRouteImport } from './routes/_authenticated.app.corretor'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated.app.chat'
import { Route as AuthenticatedAppApresentacoesRouteImport } from './routes/_authenticated.app.apresentacoes'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated.app.admin'
import { Route as ApiPublicWebhookEscalepayRouteImport } from './routes/api/public/webhook.escalepay'
import { Route as ApiPublicTrabalhosReceberRouteImport } from './routes/api/public/trabalhos.receber'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTradutorRoute =
  AuthenticatedAppTradutorRouteImport.update({
    id: '/tradutor',
    path: '/tradutor',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTrabalhosRoute =
  AuthenticatedAppTrabalhosRouteImport.update({
    id: '/trabalhos',
    path: '/trabalhos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppResumoRoute = AuthenticatedAppResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPlanosRoute = AuthenticatedAppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMatematicaRoute =
  AuthenticatedAppMatematicaRouteImport.update({
    id: '/matematica',
    path: '/matematica',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFerramentasRoute =
  AuthenticatedAppFerramentasRouteImport.update({
    id: '/ferramentas',
    path: '/ferramentas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCorretorRoute =
  AuthenticatedAppCorretorRouteImport.update({
    id: '/corretor',
    path: '/corretor',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppApresentacoesRoute =
  AuthenticatedAppApresentacoesRouteImport.update({
    id: '/apresentacoes',
    path: '/apresentacoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicWebhookEscalepayRoute =
  ApiPublicWebhookEscalepayRouteImport.update({
    id: '/api/public/webhook/escalepay',
    path: '/api/public/webhook/escalepay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrabalhosReceberRoute =
  ApiPublicTrabalhosReceberRouteImport.update({
    id: '/api/public/trabalhos/receber',
    path: '/api/public/trabalhos/receber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/apresentacoes': typeof AuthenticatedAppApresentacoesRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/corretor': typeof AuthenticatedAppCorretorRoute
  '/app/ferramentas': typeof AuthenticatedAppFerramentasRoute
  '/app/matematica': typeof AuthenticatedAppMatematicaRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/planos': typeof AuthenticatedAppPlanosRoute
  '/app/resumo': typeof AuthenticatedAppResumoRoute
  '/app/trabalhos': typeof AuthenticatedAppTrabalhosRoute
  '/app/tradutor': typeof AuthenticatedAppTradutorRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/trabalhos/receber': typeof ApiPublicTrabalhosReceberRoute
  '/api/public/webhook/escalepay': typeof ApiPublicWebhookEscalepayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/apresentacoes': typeof AuthenticatedAppApresentacoesRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/corretor': typeof AuthenticatedAppCorretorRoute
  '/app/ferramentas': typeof AuthenticatedAppFerramentasRoute
  '/app/matematica': typeof AuthenticatedAppMatematicaRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/planos': typeof AuthenticatedAppPlanosRoute
  '/app/resumo': typeof AuthenticatedAppResumoRoute
  '/app/trabalhos': typeof AuthenticatedAppTrabalhosRoute
  '/app/tradutor': typeof AuthenticatedAppTradutorRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/public/trabalhos/receber': typeof ApiPublicTrabalhosReceberRoute
  '/api/public/webhook/escalepay': typeof ApiPublicWebhookEscalepayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/apresentacoes': typeof AuthenticatedAppApresentacoesRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/app/corretor': typeof AuthenticatedAppCorretorRoute
  '/_authenticated/app/ferramentas': typeof AuthenticatedAppFerramentasRoute
  '/_authenticated/app/matematica': typeof AuthenticatedAppMatematicaRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/planos': typeof AuthenticatedAppPlanosRoute
  '/_authenticated/app/resumo': typeof AuthenticatedAppResumoRoute
  '/_authenticated/app/trabalhos': typeof AuthenticatedAppTrabalhosRoute
  '/_authenticated/app/tradutor': typeof AuthenticatedAppTradutorRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/trabalhos/receber': typeof ApiPublicTrabalhosReceberRoute
  '/api/public/webhook/escalepay': typeof ApiPublicWebhookEscalepayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app'
    | '/app/admin'
    | '/app/apresentacoes'
    | '/app/chat'
    | '/app/corretor'
    | '/app/ferramentas'
    | '/app/matematica'
    | '/app/perfil'
    | '/app/planos'
    | '/app/resumo'
    | '/app/trabalhos'
    | '/app/tradutor'
    | '/app/'
    | '/api/public/trabalhos/receber'
    | '/api/public/webhook/escalepay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/admin'
    | '/app/apresentacoes'
    | '/app/chat'
    | '/app/corretor'
    | '/app/ferramentas'
    | '/app/matematica'
    | '/app/perfil'
    | '/app/planos'
    | '/app/resumo'
    | '/app/trabalhos'
    | '/app/tradutor'
    | '/app'
    | '/api/public/trabalhos/receber'
    | '/api/public/webhook/escalepay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/app'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/apresentacoes'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/corretor'
    | '/_authenticated/app/ferramentas'
    | '/_authenticated/app/matematica'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/planos'
    | '/_authenticated/app/resumo'
    | '/_authenticated/app/trabalhos'
    | '/_authenticated/app/tradutor'
    | '/_authenticated/app/'
    | '/api/public/trabalhos/receber'
    | '/api/public/webhook/escalepay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicTrabalhosReceberRoute: typeof ApiPublicTrabalhosReceberRoute
  ApiPublicWebhookEscalepayRoute: typeof ApiPublicWebhookEscalepayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tradutor': {
      id: '/_authenticated/app/tradutor'
      path: '/tradutor'
      fullPath: '/app/tradutor'
      preLoaderRoute: typeof AuthenticatedAppTradutorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trabalhos': {
      id: '/_authenticated/app/trabalhos'
      path: '/trabalhos'
      fullPath: '/app/trabalhos'
      preLoaderRoute: typeof AuthenticatedAppTrabalhosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/resumo': {
      id: '/_authenticated/app/resumo'
      path: '/resumo'
      fullPath: '/app/resumo'
      preLoaderRoute: typeof AuthenticatedAppResumoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/planos': {
      id: '/_authenticated/app/planos'
      path: '/planos'
      fullPath: '/app/planos'
      preLoaderRoute: typeof AuthenticatedAppPlanosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/matematica': {
      id: '/_authenticated/app/matematica'
      path: '/matematica'
      fullPath: '/app/matematica'
      preLoaderRoute: typeof AuthenticatedAppMatematicaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ferramentas': {
      id: '/_authenticated/app/ferramentas'
      path: '/ferramentas'
      fullPath: '/app/ferramentas'
      preLoaderRoute: typeof AuthenticatedAppFerramentasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/corretor': {
      id: '/_authenticated/app/corretor'
      path: '/corretor'
      fullPath: '/app/corretor'
      preLoaderRoute: typeof AuthenticatedAppCorretorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/apresentacoes': {
      id: '/_authenticated/app/apresentacoes'
      path: '/apresentacoes'
      fullPath: '/app/apresentacoes'
      preLoaderRoute: typeof AuthenticatedAppApresentacoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/webhook/escalepay': {
      id: '/api/public/webhook/escalepay'
      path: '/api/public/webhook/escalepay'
      fullPath: '/api/public/webhook/escalepay'
      preLoaderRoute: typeof ApiPublicWebhookEscalepayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trabalhos/receber': {
      id: '/api/public/trabalhos/receber'
      path: '/api/public/trabalhos/receber'
      fullPath: '/api/public/trabalhos/receber'
      preLoaderRoute: typeof ApiPublicTrabalhosReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppApresentacoesRoute: typeof AuthenticatedAppApresentacoesRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppCorretorRoute: typeof AuthenticatedAppCorretorRoute
  AuthenticatedAppFerramentasRoute: typeof AuthenticatedAppFerramentasRoute
  AuthenticatedAppMatematicaRoute: typeof AuthenticatedAppMatematicaRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppPlanosRoute: typeof AuthenticatedAppPlanosRoute
  AuthenticatedAppResumoRoute: typeof AuthenticatedAppResumoRoute
  AuthenticatedAppTrabalhosRoute: typeof AuthenticatedAppTrabalhosRoute
  AuthenticatedAppTradutorRoute: typeof AuthenticatedAppTradutorRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppApresentacoesRoute: AuthenticatedAppApresentacoesRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppCorretorRoute: AuthenticatedAppCorretorRoute,
  AuthenticatedAppFerramentasRoute: AuthenticatedAppFerramentasRoute,
  AuthenticatedAppMatematicaRoute: AuthenticatedAppMatematicaRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppPlanosRoute: AuthenticatedAppPlanosRoute,
  AuthenticatedAppResumoRoute: AuthenticatedAppResumoRoute,
  AuthenticatedAppTrabalhosRoute: AuthenticatedAppTrabalhosRoute,
  AuthenticatedAppTradutorRoute: AuthenticatedAppTradutorRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicTrabalhosReceberRoute: ApiPublicTrabalhosReceberRoute,
  ApiPublicWebhookEscalepayRoute: ApiPublicWebhookEscalepayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
